import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Nev from "@/Components/Nev";
import Content from "@/Components/Content";
import Footer from "@/Components/Footer";
import Sidebar from "@/Components/Sidebar";
import { useEffect, useState } from "react";
import { toast, Toaster } from "react-hot-toast";
import { Radio } from "@material-tailwind/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [color, setColor] = useState(false);
  const [data, setData] = useState([]);
  useEffect(() => {
    fetch("https://openapi.programming-hero.com/api/quiz/5")
      .then((res) => res.json())
      .then((data) => setData(data.data.questions))
      .catch((err) => console.log(err));
  }, []);
  const notify = (ans) => toast(ans);
  const handleAns = (correctAnswer, option) => {
    if (correctAnswer == option) {
      toast.success("Congratulation");
    } else {
      toast.error("Oh");
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-between bg-white">
        <Toaster />
        <div className="w-10/12 text-black bg-white">
          <div className="fixed top-0 left-0 right-0 w-10/12 bg-slate-50">
            <Nev />
          </div>
          <div className="mt-16">{/* <Content /> */}</div>
          <div className="fixed bottom-0 left-0 right-0 w-10/12 bg-slate-50">
            <Footer setValue={setColor} color={color}></Footer>
          </div>
          <div className="pb-8 ">
            {data.map((item, index) => (
              <div key={index}>
                <div className="p-5 m-5 mt-2 bg-white border-4 rounded-md shadow-2xl border-sky-300 md:m-10">
                  <div className="blog md:flex md:justify-between">
                    <h1 className="text-2xl font-semibold text-black">
                      Quiz :{" "}
                      {item.question.replace("<p>", " ").replace("</p>", " ")}
                    </h1>
                  </div>
                  <form className="grid grid-cols-1 gap-4 mt-3 md:grid-cols-2">
                    {item.options.map((option, id) => (
                      <label
                        key={id}
                        className="flex items-center p-3 mt-3 font-medium text-black rounded-md shadow-xl bg-sky-200"
                      >
                        {/* <input
                          onClick={() => handleAns(item.correctAnswer, option)}
                          type="radio"
                          name="radio-6"
                          className="radio radio-accent"
                        /> */}
                        <Radio
                          onClick={() => handleAns(item.correctAnswer, option)}
                          id="ripple-on"
                          name="type"
                          className="border-2 border-primary-blue"
                          ripple={false}
                        />{" "}
                        <p className="ml-2">{option}</p>
                      </label>
                    ))}
                  </form>
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className="fixed top-0 right-0 w-2/12 bg-white">
          <div>
            <Sidebar value={color}></Sidebar>
          </div>
        </div>
      </main>
    </>
  );
}
