import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Nev from "@/Components/Nev";
import Content from "@/Components/Content";
import Footer from "@/Components/Footer";
import Sidebar from "@/Components/Sidebar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [color, setColor] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-between bg-white">
        <div className="w-10/12 text-black bg-white">
          <div className="fixed top-0 left-0 right-0 w-10/12 bg-slate-50">
            <Nev />
          </div>
          <div className="mt-16">
            <Content />
          </div>
          <div className="fixed bottom-0 left-0 right-0 w-10/12 bg-slate-50">
            <Footer setValue={setColor} color={color}></Footer>
          </div>
          <p className="text-black">
            same image you have to design and host online on vercel.app and
            share the url. When we click on next button then right side button
            became green, when click on review then became yellow, when clck on
            dump then it became whitesame image you have to design and host
            online on vercel.app and share the url. When we click on next button
            then right side button became green, when click on review then
            became yellow, when clck on dump then it became whitesame image you
            have to design and host online on vercel.app and share the url. When
            we click on next button then right side button became green, when
            click on review then became yellow, when clck on dump then it became
            whitesame image you have to design and host online on vercel.app and
            share the url. When we click on next button then right side button
            became green, when click on review then became yellow, when clck on
            dump then it became whitesame image you have to design and host
            online on vercel.app and share the url. When we click on next button
            then right side button became green, when click on review then
            became yellow, when clck on dump then it became whitesame image you
            have to design and host online on vercel.app and share the url. When
            we click on next button then right side button became green, when
            click on review then became yellow, when clck on dump then it became
            whitesame image you have to design and host online on vercel.app and
            share the url. When we click on next button then right side button
            became green, when click on review then became yellow, when clck on
            dump then it became whitesame image you have to design and host
            online on vercel.app and share the url. When we click on next button
            then right side button became green, when click on review then
            became yellow, when clck on dump then it became whitesame image you
            have to design and host online on vercel.app and share the url. When
            we click on next button then right side button became green, when
            click on review then became yellow, when clck on dump then it became
            whitesame image you have to design and host online on vercel.app and
            share the url. When we click on next button then right side button
            became green, when click on review then became yellow, when clck on
            dump then it became whitesame image you have to design and host
            online on vercel.app and share the url. When we click on next button
            then right side button became green, when click on review then
            became yellow, when clck on dump then it became whitesame image you
            have to design and host online on vercel.app and share the url. When
            we click on next button then right side button became green, when
            click on review then became yellow, when clck on dump then it became
            whitesame image you have to design and host online on vercel.app and
            share the url. When we click on next button then right side button
            became green, when click on review then became yellow, when clck on
            dump then it became whitesame image you have to design and host
            online on vercel.app and share the url. When we click on next button
            then right side button became green, when click on review then
            became yellow, when clck on dump then it became whitesame image you
            have to design and host online on vercel.app and share the url. When
            we click on next button then right side button became green, when
            click on review then became yellow, when clck on dump then it became
            whitesame image you have to design and host online on vercel.app and
            share the url. When we click on next button then right side button
            became green, when click on review then became yellow, when clck on
            dump then it became whitesame image you have to design and host
            online on vercel.app and share the url. When we click on next button
            then right side button became green, when click on review then
            became yellow, when clck on dump then it became whitesame image you
            have to design and host online on vercel.app and share the url. When
            we click on next button then right side button became green, when
            click on review then became yellow, when clck on dump then it became
            whitesame image you have to design and host online on vercel.app and
            share the url. When we click on next button then right side button
            became green, when click on review then became yellow, when clck on
            dump then it became whitesame image you have to design and host
            online on vercel.app and share the url. When we click on next button
            then right side button became green, when click on review then
            became yellow, when clck on dump then it became whitesame image you
            have to design and host online on vercel.app and share the url. When
            we click on next button then right side button became green, when
            click on review then became yellow, when clck on dump then it became
            whitesame image you have to design and host online on vercel.app and
            share the url. When we click on next button then right side button
            became green, when click on review then became yellow, when clck on
            dump then it became whitesame image you have to design and host
            online on vercel.app and share the url. When we click on next button
            then right side button became green, when click on review then
            became yellow, when clck on dump then it became white same image you
            have to design and host online on vercel.app and share the url. When
            we click on next button then right side button became green, when
            click on review then became yellow, when clck on dump then it became
            whitesame image you have to design and host online on vercel.app and
            share the url. When we click on next button then right side button
            became green, when click on review then became yellow, when clck on
            dump then it became whitesame image you have to design and host
            online on vercel.app and share the url. When we click on next button
            then right side button became green, when click on review then
            became yellow, when clck on dump then it became whitesame image you
            have to design and host online on vercel.app and share the url. When
            we click on next button then right side button became green, when
            click on review then became yellow, when clck on dump then it became
            whitesame image you have to design and host online on vercel.app and
            share the url. When we click on next button then right side button
            became green, when click on review then became yellow, when clck on
            dump then it became whitevsame image you have to design and host
            online on vercel.app and share the url. When we click on next button
            then right side button became green, when click on review then
            became yellow, when clck on dump then it became whitesame image you
            have to design and host online on vercel.app and share the url. When
            we click on next button then right side button became green, when
            click on review then became yellow, when clck on dump then it became
            whitesame image you have to design and host online on vercel.app and
            share the url. When we click on next button then right side button
            became green, when click on review then became yellow, when clck on
            dump then it became whitesame image you have to design and host
            online on vercel.app and share the url. When we click on next button
            then right side button became green, when click on review then
            became yellow, when clck on dump then it became whitesame image you
            have to design and host online on vercel.app and share the url. When
            we click on next button then right side button became green, when
            click on review then became yellow, when clck on dump then it became
            whitesame image you have to design and host online on vercel.app and
            share the url. When we click on next button then right side button
            became green, when click on review then became yellow, when clck on
            dump then it became whitesame image you have to design and host
            online on vercel.app and share the url. When we click on next button
            then right side button became green, when click on review then
            became yellow, when clck on dump then it became whitesame image you
            have to design and host online on vercel.app and share the url. When
            we click on next button then right side button became green, when
            click on review then became yellow, when clck on dump then it became
            whitesame image you have to design and host online on vercel.app and
            share the url. When we click on next button then right side button
            became green, when click on review then became yellow, when clck on
            dump then it became whitesame image you have to design and host
            online on vercel.app and share the url. When we click on next button
            then right side button became green, when click on review then
            became yellow, when clck on dump then it became whitesame image you
            have to design and host online on vercel.app and share the url. When
            we click on next button then right side button became green, when
            click on review then became yellow, when clck on dump then it became
            whitesame image you have to design and host online on vercel.app and
            share the url. When we click on next button then right side button
            became green, when click on review then became yellow, when clck on
            dump then it became white
          </p>
        </div>
        <div className="fixed top-0 right-0 w-2/12 bg-white">
          <div>
            <Sidebar value={color}></Sidebar>
          </div>
        </div>
      </main>
    </>
  );
}
