import Head from "next/head";
import Nev from "@/Components/Nev";
import Content from "@/Components/Content";
import Footer from "@/Components/Footer";
import Sidebar from "@/Components/Sidebar";
import { useState } from "react";
import { Toaster } from "react-hot-toast";

export default function Home() {
  const [color, setColor] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-between bg-white">
        <Toaster />
        <div className="w-10/12 text-black bg-white">
          <div className="fixed top-0 left-0 right-0 w-10/12 bg-slate-50">
            <Nev />
          </div>
          <div className="mt-16">{/* <Content /> */}</div>
          <div className="fixed bottom-0 left-0 right-0 w-10/12 bg-slate-50">
            <Footer setValue={setColor} color={color}></Footer>
          </div>
          <div>
            <Content />
          </div>
        </div>
        <div className="fixed top-0 right-0 w-2/12 bg-white">
          <div>
            <Sidebar value={color}></Sidebar>
          </div>
        </div>
      </main>
    </>
  );
}
